functions:
  - name: safe_divide
    description: Safely divide a numerator where denominator might be 0
    arguments:
      - name: numerator
        data_type: number
      - name: denominator
        data_type: number
    returns: 
      data_type: number